Parameters:
  DeploymentBucketName:
    Description: The name of the description bucket
    Type: String

  RoleArn:
    Description: The ARN from the Role that will manage the cloudformation stack
    Type: String

Resources:
  DeploymentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Ref: DeploymentBucketName

  DeploymentBucketPolicy:
    DependsOn:
      - DeploymentBucket
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: DeploymentBucket
      PolicyDocument:
        Statement:
          - Sid: Access to Cloudformation Role
            Effect: Allow
            Principal:
              AWS:
                - Ref: RoleArn
            Action:
              - s3:*
            Resource:
              - Fn::GetAtt:
                  - DeploymentBucket
                  - Arn
              - Fn::Join:
                  - ''
                  - - Fn::GetAtt:
                      - DeploymentBucket
                      - Arn
                    - '/*'