Resources:
  Macro:
    Type: AWS::CloudFormation::Macro
    Properties:
      FunctionName:
        Fn::GetAtt:
          - GetStackLastUpdatedTimeLambdaFunction
          - Arn
      Name: StackLastUpdatedTime