# TO CHECK ACTION TYPES
# https://docs.aws.amazon.com/codepipeline/latest/userguide/reference-pipeline-structure.html#actions-valid-providers

Resources:
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: ${self:custom.pipeline.name}
      ArtifactStore:
        Type: S3
        Location: !Ref PipelineArtifactsS3Bucket
        EncryptionKey:
          Id: !GetAtt [KMSKey, Arn]
          Type: KMS
      RoleArn: !GetAtt [PipelineRole, Arn]
      Stages:
        - Name: GetSourceConfigurationFile
          Actions:
            - Name: GetSourceFromS3
              OutputArtifacts:
                - Name: PullRequestDataArtifact
              Region: !Ref AWS::Region
              ActionTypeId:
                Provider: S3
                Owner: AWS
                Version: 1
                Category: Source
              Configuration:
                S3Bucket: !Ref PipelineSourceS3Bucket
                S3ObjectKey: ${self:custom.source.objectKey}
                PollForSourceChanges: false
              RunOrder: 1
        - Name: GetSourceCodeBuildAndDeploy
          Actions:
            - Name: OpenNewBranch
              ActionTypeId:
                Category: Invoke
                Owner: AWS
                Provider: Lambda
                Version: 1
              RunOrder: 1
              Configuration:
                FunctionName: !Ref OpenNewBranchLambdaFunction
              InputArtifacts:
                - Name: PullRequestDataArtifact
              OutputArtifacts:
                - Name: SourceCodeArtifact
              Region: !Ref AWS::Region
            - Fn::If:
              - IsServerlessEnabled
              - Name: BuildServerless
                ActionTypeId:
                  Category: Build
                  Owner: AWS
                  Provider: CodeBuild
                  Version: 1
                InputArtifacts:
                  - Name: SourceCodeArtifact
                OutputArtifacts:
                  - Name: QAServerlessArtifact
                  - Name: ProductionServerlessArtifact
                Configuration:
                  ProjectName:
                    Ref: ServerlessBuildProject
                RunOrder: 2
              - !Ref AWS::NoValue
            - Fn::If:
              - IsWebpackEnabled
              - Name: BuildWebpack
                ActionTypeId:
                  Category: Build
                  Owner: AWS
                  Provider: CodeBuild
                  Version: 1
                InputArtifacts:
                  - Name: SourceCodeArtifact
                OutputArtifacts:
                  - Name: QAWebpackArtifact
                  - Name: ProductionWebpackArtifact
                Configuration:
                  ProjectName:
                    Ref: WebpackBuildProject
                RunOrder: 2
              - !Ref AWS::NoValue
            - Fn::If:
              - IsServerlessEnabled
              - Name: DeployFunctionsQA
                ActionTypeId:
                  Category: Build
                  Owner: AWS
                  Provider: CodeBuild
                  Version: 1
                InputArtifacts:
                  - Name: QAServerlessArtifact
                Configuration:
                  ProjectName:
                    Ref: DeployFunctionsProject
                  EnvironmentVariables: |
                    [
                      {
                        "name":"ENVIRONMENT",
                        "type":"PLAINTEXT",
                        "value":"qa"
                      },
                      {
                        "name":"QA_ROLE_NAME",
                        "type":"PLAINTEXT",
                        "value":"${self:custom.qa.roleName}"
                      },
                      {
                        "name":"QA_ACCOUNT",
                        "type":"PLAINTEXT",
                        "value":"${self:custom.qa.accountId}"
                      }
                    ]
                RunOrder: 3
              - !Ref AWS::NoValue
            - Fn::If:
              - IsServerlessEnabled
              - Name: BuildCloudformationQA
                ActionTypeId:
                  Category: Deploy
                  Owner: AWS
                  Provider: CloudFormation
                  Version: 1
                InputArtifacts:
                  - Name: QAServerlessArtifact
                Configuration:
                  ActionMode: CREATE_UPDATE
                  StackName: ${self:custom.cloudformation.stackName}
                  Capabilities: CAPABILITY_IAM,CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
                  TemplatePath: QAServerlessArtifact::cloudformation-template-update-stack.json
                  RoleArn: ${self:custom.qa.cloudformation.roleArn}
                RoleArn: ${self:custom.qa.roleArn}
                RunOrder: 4
              - !Ref AWS::NoValue
            - Fn::If:
              - IsS3SyncEnabled
              - Name: SyncPackageToS3QA
                ActionTypeId:
                  Category: Build
                  Owner: AWS
                  Provider: CodeBuild
                  Version: 1
                InputArtifacts:
                  - Name: !If [IsS3SyncFromWebpack, 'QAWebpackArtifact', !If [IsS3SyncFromServerless, 'QAServerlessArtifact', !Ref AWS::NoValue]]
                Configuration:
                  ProjectName: !Ref SyncPackageToS3Project
                  EnvironmentVariables: |
                    [
                      {
                        "name":"BUCKET_NAME",
                        "type":"PLAINTEXT",
                        "value":"${self:custom.syncS3.bucket}"
                      }
                    ]
                RunOrder: 5
              - !Ref AWS::NoValue
            - Fn::If:
              - IsDatabaseMigrationEnabled
              - Name: MigrateDBAndGraphQLActionQA
                ActionTypeId:
                  Category: Build
                  Owner: AWS
                  Provider: CodeBuild
                  Version: 1
                InputArtifacts:
                  - Name: SourceCodeArtifact
                Configuration:
                  PrimarySource: SourceCodeArtifact
                  ProjectName:
                    Ref: MigrateDatabase
                  EnvironmentVariables: |
                    [
                      {
                        "name":"ENVIRONMENT",
                        "type":"PLAINTEXT",
                        "value":"qa"
                      }
                    ]
                RunOrder: 5
              - !Ref AWS::NoValue
            - Fn::If:
              - IsValidationEnabled
              - Name: NotifyForValidation
                ActionTypeId:
                  Category: Approval
                  Owner: AWS
                  Provider: Manual
                  Version: 1
                Configuration:
                  NotificationArn: !Ref NotifyForValidationTopic
                RunOrder: 6
              - !Ref AWS::NoValue
            - Fn::If:
              - IsPullRequestEnabled
              - Name: OpenPullRequest
                ActionTypeId:
                  Category: Approval
                  Owner: AWS
                  Provider: Manual
                  Version: 1
                Configuration:
                  NotificationArn: !Ref OpenPullRequestTopic
                RunOrder: 7
              - !Ref AWS::NoValue
            - Fn::If:
              - IsServerlessEnabled
              - Name: DeployFunctionsProduction
                ActionTypeId:
                  Category: Build
                  Owner: AWS
                  Provider: CodeBuild
                  Version: 1
                InputArtifacts:
                  - Name: ProductionServerlessArtifact
                Configuration:
                  ProjectName:
                    Ref: DeployFunctionsProject
                  EnvironmentVariables: |
                    [
                      {
                        "name":"ENVIRONMENT",
                        "type":"PLAINTEXT",
                        "value":"production"
                      }
                    ]
                RunOrder: 9
              - !Ref AWS::NoValue
            - Fn::If:
              - IsServerlessEnabled
              - Name: BuildCloudformationProduction
                ActionTypeId:
                  Category: Deploy
                  Owner: AWS
                  Provider: CloudFormation
                  Version: 1
                InputArtifacts:
                  - Name: ProductionServerlessArtifact
                Configuration:
                  ActionMode: CREATE_UPDATE
                  StackName: ${self:custom.cloudformation.stackName}
                  Capabilities: CAPABILITY_IAM,CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
                  TemplatePath: ProductionServerlessArtifact::cloudformation-template-update-stack.json
                  RoleArn: !GetAtt [CloudFormationRole, Arn]
                RunOrder: 10
              - !Ref AWS::NoValue
            - Fn::If:
              - IsDatabaseMigrationEnabled
              - Name: MigrateDBAndGraphQLActionProduction
                ActionTypeId:
                  Category: Build
                  Owner: AWS
                  Provider: CodeBuild
                  Version: 1
                InputArtifacts:
                  - Name: SourceCodeArtifact
                Configuration:
                  PrimarySource: SourceCodeArtifact
                  ProjectName:
                    Ref: MigrateDatabase
                  EnvironmentVariables: |
                    [
                      {
                        "name":"ENVIRONMENT",
                        "type":"PLAINTEXT",
                        "value":"production"
                      }
                    ]
                RunOrder: 11
              - !Ref AWS::NoValue
            - Fn::If:
              - IsServerlessEnabled
              - Name: SaveCloudformationTemplatesToS3
                ActionTypeId:
                  Category: Invoke
                  Owner: AWS
                  Provider: Lambda
                  Version: 1
                Configuration:
                  FunctionName: !Ref SaveCFTemplateLambdaFunction
                InputArtifacts:
                  - Name: QAServerlessArtifact
                  - Name: ProductionServerlessArtifact
                RunOrder: 12
              - !Ref AWS::NoValue
        # IT'S IMPORTANT THAT THIS IS ANOTHER STAGE SINCE THE PIPELINE NEEDS AT LEAST 2 STAGES
        - Name: NotifySuccess
          Actions:
            - Name: NotifySuccess
              ActionTypeId:
                Category: Invoke
                Owner: AWS
                Provider: Lambda
                Version: 1
              Configuration:
                FunctionName: !Ref NotifySuccessLambdaFunction
                UserParameters: |
                  {
                    "pipelineName": "${self:custom.pipeline.name}"
                  }
              RunOrder: 1