Resources:
  DeployFunctionsProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: ${self:custom.deployFunctions.projectName}
      Description: Fetch the deployment folder that Serverless has defined when creating the stacks templates, and upload the Lambdas and individual stack templates to the correct paths inside the ServerlessDeploymentBucket, whose name is available in serverless-state.json
      Artifacts:
        Type: NO_ARTIFACTS
      EncryptionKey: !GetAtt [KMSKey, Arn]
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
        EnvironmentVariables:
          - Name: QA_ACCOUNT
            Type: PLAINTEXT
            Value: ${self:custom.qa.accountId}
          - Name: QA_ROLE_NAME
            Type: PLAINTEXT
            Value: ${self:custom.qa.roleName}
      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED
      Source:
        Type: NO_SOURCE
        BuildSpec: |
          ${fileToString:resources/buildspecs/deployFunctions.yml}
      ServiceRole: !GetAtt [CodebuildRole, Arn]
      TimeoutInMinutes: 30
