Resources:
  CodebuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ${self:custom.codebuild.roleName}
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  CodebuildRolePolicy:
    DependsOn:
      - CodebuildRole
      - KMSKey
    Type: AWS::IAM::Policy
    Properties:
      Roles:
        - !Ref CodebuildRole
      PolicyName: ${self:custom.codebuild.policyName}
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - cloudformation:ListStackResources
            Resource:
              - '*'
          - Effect: Allow
            Action:
              - codepipeline:PutJobSuccessResult
              - codepipeline:PutJobFailureResult
            Resource:
              - '*'
          - Effect: Allow
            Action:
              - route53:ListHostedZonesByName
            Resource:
              - '*'
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Resource:
              - ${self:custom.qa.roleArn}
          - Effect: Allow
            Action:
              - rds:DescribeDBInstances
              - secretsmanager:GetSecretValue
              - lambda:GetLayerVersion
              - lambda:ListLayers
              - lambda:PublishLayerVersion
              - lambda:UpdateFunctionConfiguration
              - cognito-idp:ListUserPools
            Resource: '*'
          - Effect: Allow
            Action:
              - s3:PutObject
              - s3:GetBucketPolicy
              - s3:GetObject
              - s3:ListBucket
            Resource: '*'
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: arn:aws:logs:*:*:*
          - Effect: Allow
            Action:
              - kms:*
            Resource:
              - !GetAtt [KMSKey, Arn]
