version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - echo 'install'
  build:
    commands:
      - destination="s3://$SLS_BUCKET/$SLS_PATH"
      - echo $destination
      # ASSUMING QA ROLE IF ONE QA TO DO EVERYTHING ON BEHALF OF THAT USER
      - |
        if [ "$ENVIRONMENT" = "qa" ]
        then
          ${escapedFileToString:resources/buildspecs/assumeQARole.sh}
        fi

      - aws s3 sync . $destination
