version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install --silent --no-progress -g serverless@$SERVERLESS_VERSION
      - npm install --silent
      - |
        ${self:custom.migrate.install}
  build:
    commands:
      # SETTING VARIABLES THAT SLS WILL USE
      - export StackName="$STACK_NAME"
      
      # ASSUMING QA ROLE IF ONE QA TO DO EVERYTHING ON BEHALF OF THAT USER
      - |
        if [ "$ENVIRONMENT" = "qa" ]
        then
          ${escapedFileToString:resources/buildspecs/assumeQARole.sh}
        fi

      - ${self:custom.migrate.command}
cache:
  paths:
    - 'node_modules/**/*'