version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm config set unsafe-perm=true
      - npm install --silent --no-progress -g serverless@$SERVERLESS_VERSION
      - npm install --silent
  pre_build:
    commands:
      - |
        ${self:custom.serverless.prebuild}
  build: # only runs if pre-build succeeded
    commands:
      - mkdir -p $QA_TARGET_DIR
      - mkdir -p $PROD_TARGET_DIR

      - ${self:custom.serverless.packageProduction}
      - cp -R ${self:custom.serverless.packageOutputFolder}/. $PROD_TARGET_DIR/
      - rm -rf ${self:custom.serverless.packageOutputFolder}
      
      # ASSUMING QA ROLE IF ONE QA TO DO EVERYTHING ON BEHALF OF THAT USER
      - ${fileToString:resources/buildspecs/assumeQARole.sh}
        
      - ${self:custom.serverless.packageQA}
      - cp -R ${self:custom.serverless.packageOutputFolder}/. $QA_TARGET_DIR/
      - rm -rf ${self:custom.serverless.packageOutputFolder}

cache:
  paths:
    - 'node_modules/**/*'

artifacts:
  secondary-artifacts:
    ${self:custom.serverless.stateQA}:
      base-directory: $QA_TARGET_DIR/
      files:
        - serverless-state.json
    ${self:custom.serverless.artifactNameQA}:
      name: serverless-artifact.zip
      base-directory: $QA_TARGET_DIR/
      files:
        - '**/*'
    ${self:custom.serverless.stateProduction}:
      base-directory: $PROD_TARGET_DIR/
      files:
        - serverless-state.json
    ${self:custom.serverless.artifactNameProduction}:
      name: serverless-artifact.zip
      base-directory: $PROD_TARGET_DIR/
      files:
        - '**/*'